# Generated by Django 4.1.1 on 2022-10-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp',
            old_name='is_active',
            new_name='is_read',
        ),
    ]
