# Generated by Django 4.1.1 on 2022-11-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_todoapp_options_alter_todoapp_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todoapp',
            table=None,
        ),
    ]
