# Generated by Django 4.1.1 on 2022-11-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_todoapp_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
    ]
