# Generated by Django 4.1.1 on 2022-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_is_read_todoapp_is_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='created',
            field=models.DateField(),
        ),
    ]
