# Generated by Django 4.1.1 on 2022-11-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_todoapp_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp',
            name='slug',
        ),
    ]
